// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RankCSS.Infra.Data.EF;

namespace RankCSS.Infra.Data.Migrations
{
    [DbContext(typeof(RankContext))]
    partial class RankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RankCSS.Business.Entidades.Jogador", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("varchar(20) CHARACTER SET utf8mb4")
                        .HasMaxLength(20);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Jogador");
                });

            modelBuilder.Entity("RankCSS.Business.Entidades.Partida", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Mapa")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.HasKey("ID");

                    b.ToTable("Partida");
                });

            modelBuilder.Entity("RankCSS.Business.Entidades.Rodada", b =>
                {
                    b.Property<Guid>("JogadorID")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("PartidaID")
                        .HasColumnType("char(36)");

                    b.Property<int?>("BombasDefusadas")
                        .HasColumnType("int");

                    b.Property<int?>("BombasPlantadas")
                        .HasColumnType("int");

                    b.Property<int?>("FogoAmigo")
                        .HasColumnType("int");

                    b.Property<int>("Matou")
                        .HasColumnType("int");

                    b.Property<int>("Morreu")
                        .HasColumnType("int");

                    b.Property<int?>("TiroCabeca")
                        .HasColumnType("int");

                    b.HasKey("JogadorID", "PartidaID");

                    b.HasIndex("PartidaID");

                    b.ToTable("Rodada");
                });

            modelBuilder.Entity("RankCSS.Business.Entidades.Rodada", b =>
                {
                    b.HasOne("RankCSS.Business.Entidades.Jogador", "Jogador")
                        .WithMany("Rodadas")
                        .HasForeignKey("JogadorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RankCSS.Business.Entidades.Partida", "Partida")
                        .WithMany("Rodadas")
                        .HasForeignKey("PartidaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
